<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <MauiVersion>10.0.90</MauiVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <RunAOTCompilation>false</RunAOTCompilation>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <AndroidLinkMode>None</AndroidLinkMode>
  </PropertyGroup>
</Project>

