namespace NuvyntraLabs.Lumina.Core;

public static class BankSeed
{
    public const string Collection = "bank";

    public static IReadOnlyList<CatalogItem> Items { get; } =
    [
            new CatalogItem { Id = "bank-001", Title = "Email", Subtitle = "demo@aether.bank", Group = "SignIn" },
            new CatalogItem { Id = "bank-002", Title = "Password", Subtitle = "secret", Group = "SignIn" },
            new CatalogItem { Id = "bank-003", Title = "PIN", Subtitle = "••••18", Group = "PinLock" },
            new CatalogItem { Id = "bank-004", Title = "Current · 8841", Subtitle = "£4,812.20", Group = "Dashboard" },
            new CatalogItem { Id = "bank-005", Title = "Savings · 2290", Subtitle = "£18,440.00", Group = "Dashboard" },
            new CatalogItem { Id = "bank-006", Title = "USD travel", Subtitle = "$1,240.00", Group = "Dashboard" },
            new CatalogItem { Id = "bank-007", Title = "Current · 8841", Subtitle = "£4,812.20", Group = "Accounts" },
            new CatalogItem { Id = "bank-008", Title = "Savings · 2290", Subtitle = "£18,440.00", Group = "Accounts" },
            new CatalogItem { Id = "bank-009", Title = "USD travel", Subtitle = "$1,240.00", Group = "Accounts" },
            new CatalogItem { Id = "bank-010", Title = "Available", Subtitle = "£4,812.20", Group = "AccountDetail" },
            new CatalogItem { Id = "bank-011", Title = "Pending", Subtitle = "£42.00", Group = "AccountDetail" },
            new CatalogItem { Id = "bank-012", Title = "IBAN", Subtitle = "GB82 AETH 4044 8841", Group = "AccountDetail" },
            new CatalogItem { Id = "bank-013", Title = "Ada Cole", Subtitle = "···· 4418", Group = "Cards" },
            new CatalogItem { Id = "bank-014", Title = "Travel metal", Subtitle = "···· 2290", Group = "Cards" },
            new CatalogItem { Id = "bank-015", Title = "Limit", Subtitle = "£1,500", Group = "CardDetail" },
            new CatalogItem { Id = "bank-016", Title = "Contactless", Subtitle = "On", Group = "CardDetail" },
            new CatalogItem { Id = "bank-017", Title = "Frozen", Subtitle = "Off", Group = "CardDetail" },
            new CatalogItem { Id = "bank-018", Title = "To", Subtitle = "Lin Park", Group = "Transfer" },
            new CatalogItem { Id = "bank-019", Title = "Amount", Subtitle = "£85.00", Group = "Transfer" },
            new CatalogItem { Id = "bank-020", Title = "Ref", Subtitle = "Dinner", Group = "Transfer" },
            new CatalogItem { Id = "bank-021", Title = "Lin Park", Subtitle = "40-12-88 · 22901122", Group = "Payees" },
            new CatalogItem { Id = "bank-022", Title = "Harbour Market", Subtitle = "sort 20-00-00", Group = "Payees" },
            new CatalogItem { Id = "bank-023", Title = "Council", Subtitle = "£142 · 20 Sep", Group = "Bills" },
            new CatalogItem { Id = "bank-024", Title = "Thames", Subtitle = "£38 · 22 Sep", Group = "Bills" },
            new CatalogItem { Id = "bank-025", Title = "Due", Subtitle = "20 Sep", Group = "BillDetail" },
            new CatalogItem { Id = "bank-026", Title = "Amount", Subtitle = "£142", Group = "BillDetail" },
            new CatalogItem { Id = "bank-027", Title = "Account", Subtitle = "Current", Group = "BillDetail" },
            new CatalogItem { Id = "bank-028", Title = "Aurora 80", Subtitle = "+1.4% YTD", Group = "Invest" },
            new CatalogItem { Id = "bank-029", Title = "Cash plus", Subtitle = "+0.6%", Group = "Invest" },
            new CatalogItem { Id = "bank-030", Title = "Value", Subtitle = "£9,220", Group = "InvestDetail" },
            new CatalogItem { Id = "bank-031", Title = "ISIN", Subtitle = "IE00B4L5Y983", Group = "InvestDetail" },
            new CatalogItem { Id = "bank-032", Title = "Risk", Subtitle = "5 / 7", Group = "InvestDetail" },
            new CatalogItem { Id = "bank-033", Title = "Address", Subtitle = "14 Harbour Walk", Group = "Kyc" },
            new CatalogItem { Id = "bank-034", Title = "Occupation", Subtitle = "Engineer", Group = "Kyc" },
            new CatalogItem { Id = "bank-035", Title = "Source", Subtitle = "Salary", Group = "Kyc" },
            new CatalogItem { Id = "bank-036", Title = "Aug 2026", Subtitle = "Current.pdf", Group = "Statements" },
            new CatalogItem { Id = "bank-037", Title = "Jul 2026", Subtitle = "Current.pdf", Group = "Statements" },
            new CatalogItem { Id = "bank-038", Title = "FX", Subtitle = "$200 → £156.40", Group = "Invoice" },
            new CatalogItem { Id = "bank-039", Title = "Fee", Subtitle = "£0.00", Group = "Invoice" },
            new CatalogItem { Id = "bank-040", Title = "Studio loan", Subtitle = "£12,400 left", Group = "Loans" },
            new CatalogItem { Id = "bank-041", Title = "Overdraft", Subtitle = "£250 unused", Group = "Loans" },
            new CatalogItem { Id = "bank-042", Title = "Next", Subtitle = "£220 on 1 Oct", Group = "LoanDetail" },
            new CatalogItem { Id = "bank-043", Title = "End", Subtitle = "2029-04", Group = "LoanDetail" },
            new CatalogItem { Id = "bank-044", Title = "Balance", Subtitle = "8 420", Group = "Rewards" },
            new CatalogItem { Id = "bank-045", Title = "Rate", Subtitle = "1% debit", Group = "Rewards" },
            new CatalogItem { Id = "bank-046", Title = "Next", Subtitle = "Market crate", Group = "Rewards" },
            new CatalogItem { Id = "bank-047", Title = "Padhy Studio", Subtitle = "IN · HDFC", Group = "Beneficiaries" },
            new CatalogItem { Id = "bank-048", Title = "Lina Chen", Subtitle = "SG · DBS", Group = "Beneficiaries" },
            new CatalogItem { Id = "bank-049", Title = "Aether", Subtitle = "We froze the travel card.", Group = "Support" },
            new CatalogItem { Id = "bank-050", Title = "You", Subtitle = "Thank you — unlock Friday.", Group = "Support" },
            new CatalogItem { Id = "bank-051", Title = "£85 to Lin Park", Subtitle = "Just now · Faster Payments", Group = "Notifications" },
            new CatalogItem { Id = "bank-052", Title = "Card tap · Harbour Market", Subtitle = "Today · £14.20 debit", Group = "Notifications" },
            new CatalogItem { Id = "bank-058", Title = "Salary in", Subtitle = "12 Sep · £3,200.00", Group = "Notifications" },
            new CatalogItem { Id = "bank-059", Title = "Travel card frozen", Subtitle = "Yesterday · you locked it", Group = "Notifications" },
            new CatalogItem { Id = "bank-053", Title = "Lock after", Subtitle = "30 s", Group = "AppLock" },
            new CatalogItem { Id = "bank-054", Title = "Biometric", Subtitle = "On", Group = "AppLock" },
            new CatalogItem { Id = "bank-055", Title = "Screen guard", Subtitle = "On", Group = "AppLock" },
            new CatalogItem { Id = "bank-056", Title = "Travel mode", Subtitle = "Off", Group = "Settings" },
            new CatalogItem { Id = "bank-057", Title = "Wealth", Subtitle = "On", Group = "Settings" }
    ];
}
