namespace NuvyntraLabs.Lumina.Core;

public static class CivicSeed
{
    public const string Collection = "civic";

    public static IReadOnlyList<CatalogItem> Items { get; } =
    [
            new CatalogItem { Id = "civic-001", Title = "Email", Subtitle = "demo@civic.pulse", Group = "SignIn" },
            new CatalogItem { Id = "civic-002", Title = "Password", Subtitle = "secret", Group = "SignIn" },
            new CatalogItem { Id = "civic-003", Title = "Bin day", Subtitle = "Thursday · food + recycling", Group = "Home" },
            new CatalogItem { Id = "civic-004", Title = "Bus 12", Subtitle = "4 min · Harbour Walk", Group = "Home" },
            new CatalogItem { Id = "civic-005", Title = "Market", Subtitle = "Night market 18:00", Group = "Home" },
            new CatalogItem { Id = "civic-006", Title = "Missed bin", Subtitle = "Open · 2 days", Group = "Services" },
            new CatalogItem { Id = "civic-007", Title = "Pothole", Subtitle = "Scheduled", Group = "Services" },
            new CatalogItem { Id = "civic-008", Title = "Permit", Subtitle = "Ready", Group = "Services" },
            new CatalogItem { Id = "civic-009", Title = "Ref", Subtitle = "CR-4418", Group = "RequestDetail" },
            new CatalogItem { Id = "civic-010", Title = "Crew", Subtitle = "Thursday am", Group = "RequestDetail" },
            new CatalogItem { Id = "civic-011", Title = "Photo", Subtitle = "Attached", Group = "RequestDetail" },
            new CatalogItem { Id = "civic-012", Title = "Bus 12", Subtitle = "4 min", Group = "Transit" },
            new CatalogItem { Id = "civic-013", Title = "Ferry", Subtitle = "18 min", Group = "Transit" },
            new CatalogItem { Id = "civic-014", Title = "Night", Subtitle = "00:20", Group = "Transit" },
            new CatalogItem { Id = "civic-015", Title = "Zones", Subtitle = "1–2", Group = "TicketDetail" },
            new CatalogItem { Id = "civic-016", Title = "Valid", Subtitle = "Until 04:00", Group = "TicketDetail" },
            new CatalogItem { Id = "civic-017", Title = "Fare", Subtitle = "£8.40", Group = "TicketDetail" },
            new CatalogItem { Id = "civic-018", Title = "Place", Subtitle = "Harbour library", Group = "Booking" },
            new CatalogItem { Id = "civic-019", Title = "When", Subtitle = "Thu 11:00", Group = "Booking" },
            new CatalogItem { Id = "civic-020", Title = "Seats", Subtitle = "1", Group = "Booking" },
            new CatalogItem { Id = "civic-021", Title = "Night market", Subtitle = "Thu 18:00", Group = "Events" },
            new CatalogItem { Id = "civic-022", Title = "Repair cafe", Subtitle = "Sat 10:00", Group = "Events" },
            new CatalogItem { Id = "civic-023", Title = "Where", Subtitle = "Yard B", Group = "EventDetail" },
            new CatalogItem { Id = "civic-024", Title = "Stalls", Subtitle = "42", Group = "EventDetail" },
            new CatalogItem { Id = "civic-025", Title = "Transit", Subtitle = "Bus 12", Group = "EventDetail" },
            new CatalogItem { Id = "civic-026", Title = "Bridge works", Subtitle = "Night closures from Monday", Group = "News" },
            new CatalogItem { Id = "civic-027", Title = "Crate scheme", Subtitle = "Food surplus Thursdays", Group = "News" },
            new CatalogItem { Id = "civic-028", Title = "From", Subtitle = "Mon 21 Sep", Group = "ArticleDetail" },
            new CatalogItem { Id = "civic-029", Title = "Bus 12", Subtitle = "Diverted via Aurora", Group = "ArticleDetail" },
            new CatalogItem { Id = "civic-030", Title = "Town hall", Subtitle = "0.6 mi · until 16:00", Group = "Offices" },
            new CatalogItem { Id = "civic-031", Title = "Library", Subtitle = "0.3 mi · until 20:00", Group = "Offices" },
            new CatalogItem { Id = "civic-032", Title = "Pass", Subtitle = "Resident · Ada", Group = "Wallet" },
            new CatalogItem { Id = "civic-033", Title = "Rover", Subtitle = "Active today", Group = "Wallet" },
            new CatalogItem { Id = "civic-034", Title = "Points", Subtitle = "120", Group = "Wallet" },
            new CatalogItem { Id = "civic-035", Title = "Visitor bay", Subtitle = "Ready", Group = "Permits" },
            new CatalogItem { Id = "civic-036", Title = "Skip", Subtitle = "Expired", Group = "Permits" },
            new CatalogItem { Id = "civic-037", Title = "Bay", Subtitle = "Harbour Walk", Group = "PermitDetail" },
            new CatalogItem { Id = "civic-038", Title = "Starts", Subtitle = "Thu", Group = "PermitDetail" },
            new CatalogItem { Id = "civic-039", Title = "Fee", Subtitle = "£12", Group = "PermitDetail" },
            new CatalogItem { Id = "civic-040", Title = "Cllr Chen", Subtitle = "East quay", Group = "People" },
            new CatalogItem { Id = "civic-041", Title = "Desk", Subtitle = "Waste · 020 7946 2000", Group = "People" },
            new CatalogItem { Id = "civic-042", Title = "Bins", Subtitle = "Food + recycling Thursday.", Group = "Faq" },
            new CatalogItem { Id = "civic-043", Title = "Rover", Subtitle = "QR in Wallet.", Group = "Faq" },
            new CatalogItem { Id = "civic-044", Title = "Topic", Subtitle = "Missed bin", Group = "Contact" },
            new CatalogItem { Id = "civic-045", Title = "Message", Subtitle = "Food caddy still full.", Group = "Contact" },
            new CatalogItem { Id = "civic-046", Title = "Borough", Subtitle = "Harbour", Group = "About" },
            new CatalogItem { Id = "civic-047", Title = "Build", Subtitle = "1.0.0", Group = "About" },
            new CatalogItem { Id = "civic-048", Title = "Data", Subtitle = "Static seed", Group = "About" },
            new CatalogItem { Id = "civic-049", Title = "Tickets", Subtitle = "Wallet holds the QR.", Group = "Help" },
            new CatalogItem { Id = "civic-050", Title = "Requests", Subtitle = "Photo optional.", Group = "Help" },
            new CatalogItem { Id = "civic-051", Title = "Bin day", Subtitle = "Tomorrow 07:00", Group = "Notifications" },
            new CatalogItem { Id = "civic-052", Title = "Bus 12", Subtitle = "Short delay", Group = "Notifications" },
            new CatalogItem { Id = "civic-053", Title = "Bin reminder", Subtitle = "On", Group = "Settings" },
            new CatalogItem { Id = "civic-054", Title = "Dark paper", Subtitle = "Off", Group = "Settings" },
            new CatalogItem { Id = "civic-055", Title = "Screens", Subtitle = "22 civic routes", Group = "WhatsNew" },
            new CatalogItem { Id = "civic-056", Title = "Data", Subtitle = "NuvexaDB seed", Group = "WhatsNew" }
    ];
}
