namespace NuvyntraLabs.Lumina.Core;

public static class ClinicSeed
{
    public const string Collection = "clinic";

    public static IReadOnlyList<CatalogItem> Items { get; } =
    [
            new CatalogItem { Id = "clinic-001", Title = "Find a clinician", Subtitle = "Same-week slots.", Group = "Walkthrough" },
            new CatalogItem { Id = "clinic-002", Title = "Bring records", Subtitle = "Labs and letters in one file.", Group = "Walkthrough" },
            new CatalogItem { Id = "clinic-003", Title = "Call when needed", Subtitle = "In-app visit room.", Group = "Walkthrough" },
            new CatalogItem { Id = "clinic-004", Title = "Email", Subtitle = "demo@nuvexa.clinic", Group = "SignIn" },
            new CatalogItem { Id = "clinic-005", Title = "Password", Subtitle = "secret", Group = "SignIn" },
            new CatalogItem { Id = "clinic-006", Title = "Blood type", Subtitle = "O+", Group = "HealthProfile" },
            new CatalogItem { Id = "clinic-007", Title = "Allergies", Subtitle = "Penicillin", Group = "HealthProfile" },
            new CatalogItem { Id = "clinic-008", Title = "GP", Subtitle = "Dr. Iyer", Group = "HealthProfile" },
            new CatalogItem { Id = "clinic-009", Title = "09:30", Subtitle = "Dr. Iyer · follow-up", Group = "Home" },
            new CatalogItem { Id = "clinic-010", Title = "Lab", Subtitle = "Lipid panel ready", Group = "Home" },
            new CatalogItem { Id = "clinic-011", Title = "Rx", Subtitle = "Atorvastatin 10 mg", Group = "Home" },
            new CatalogItem { Id = "clinic-012", Title = "Thu 09:30", Subtitle = "Cardiology · Dr. Iyer", Group = "Appointments" },
            new CatalogItem { Id = "clinic-013", Title = "Mon 14:00", Subtitle = "Physio · Lin Park", Group = "Appointments" },
            new CatalogItem { Id = "clinic-014", Title = "Clinic", Subtitle = "Harbour", Group = "Booking" },
            new CatalogItem { Id = "clinic-015", Title = "Reason", Subtitle = "Follow-up", Group = "Booking" },
            new CatalogItem { Id = "clinic-016", Title = "Slot", Subtitle = "Thu 09:30", Group = "Booking" },
            new CatalogItem { Id = "clinic-017", Title = "Dr. Priya Iyer", Subtitle = "Cardiology · 4.9", Group = "Doctors" },
            new CatalogItem { Id = "clinic-018", Title = "Lin Park", Subtitle = "Physio · 4.8", Group = "Doctors" },
            new CatalogItem { Id = "clinic-019", Title = "Noah Adeyemi", Subtitle = "GP · 4.7", Group = "Doctors" },
            new CatalogItem { Id = "clinic-020", Title = "Languages", Subtitle = "EN, HI", Group = "DoctorProfile" },
            new CatalogItem { Id = "clinic-021", Title = "Next slot", Subtitle = "Thu 09:30", Group = "DoctorProfile" },
            new CatalogItem { Id = "clinic-022", Title = "Clinic", Subtitle = "Harbour 3F", Group = "DoctorProfile" },
            new CatalogItem { Id = "clinic-023", Title = "Notes", Subtitle = "Continue statin. Walk 30 min.", Group = "VisitDetail" },
            new CatalogItem { Id = "clinic-024", Title = "BP", Subtitle = "118 / 74", Group = "VisitDetail" },
            new CatalogItem { Id = "clinic-025", Title = "Next", Subtitle = "12 weeks", Group = "VisitDetail" },
            new CatalogItem { Id = "clinic-026", Title = "Atorvastatin 10 mg", Subtitle = "Nightly · 28 days", Group = "Prescriptions" },
            new CatalogItem { Id = "clinic-027", Title = "Vitamin D3", Subtitle = "Weekly", Group = "Prescriptions" },
            new CatalogItem { Id = "clinic-028", Title = "Atorvastatin", Subtitle = "£6.40 · ready", Group = "Pharmacy" },
            new CatalogItem { Id = "clinic-029", Title = "D3 2000 IU", Subtitle = "£4.10", Group = "Pharmacy" },
            new CatalogItem { Id = "clinic-030", Title = "Stock", Subtitle = "Ready in 20 min", Group = "PharmacyDetail" },
            new CatalogItem { Id = "clinic-031", Title = "Interactions", Subtitle = "Grapefruit", Group = "PharmacyDetail" },
            new CatalogItem { Id = "clinic-032", Title = "Price", Subtitle = "£6.40", Group = "PharmacyDetail" },
            new CatalogItem { Id = "clinic-033", Title = "Lipids", Subtitle = "Ready · 12 Sep", Group = "LabResults" },
            new CatalogItem { Id = "clinic-034", Title = "CBC", Subtitle = "Ready · 2 Jun", Group = "LabResults" },
            new CatalogItem { Id = "clinic-035", Title = "HbA1c", Subtitle = "Ready · 2 Jun", Group = "LabResults" },
            new CatalogItem { Id = "clinic-036", Title = "LDL", Subtitle = "2.1 mmol/L", Group = "LabDetail" },
            new CatalogItem { Id = "clinic-037", Title = "HDL", Subtitle = "1.6 mmol/L", Group = "LabDetail" },
            new CatalogItem { Id = "clinic-038", Title = "Trig", Subtitle = "1.1 mmol/L", Group = "LabDetail" },
            new CatalogItem { Id = "clinic-039", Title = "Discharge", Subtitle = "Brief.pdf", Group = "Documents" },
            new CatalogItem { Id = "clinic-040", Title = "Referral", Subtitle = "Physio letter", Group = "Documents" },
            new CatalogItem { Id = "clinic-041", Title = "Consult", Subtitle = "£85", Group = "Invoice" },
            new CatalogItem { Id = "clinic-042", Title = "ECG", Subtitle = "£40", Group = "Invoice" },
            new CatalogItem { Id = "clinic-043", Title = "Total", Subtitle = "£125", Group = "Invoice" },
            new CatalogItem { Id = "clinic-044", Title = "Dr. Iyer", Subtitle = "Your lipids look better.", Group = "Inbox" },
            new CatalogItem { Id = "clinic-045", Title = "Pharmacy", Subtitle = "Script is ready.", Group = "Inbox" },
            new CatalogItem { Id = "clinic-046", Title = "Iyer", Subtitle = "Continue the statin.", Group = "Conversation" },
            new CatalogItem { Id = "clinic-047", Title = "You", Subtitle = "Walking most evenings.", Group = "Conversation" },
            new CatalogItem { Id = "clinic-048", Title = "Peer", Subtitle = "Dr. Iyer", Group = "InCall" },
            new CatalogItem { Id = "clinic-049", Title = "Quality", Subtitle = "Good", Group = "InCall" },
            new CatalogItem { Id = "clinic-050", Title = "Duration", Subtitle = "00:12:04", Group = "InCall" },
            new CatalogItem { Id = "clinic-051", Title = "Plan", Subtitle = "Harbour Plus", Group = "Insurance" },
            new CatalogItem { Id = "clinic-052", Title = "Excess", Subtitle = "£150", Group = "Insurance" },
            new CatalogItem { Id = "clinic-053", Title = "Valid", Subtitle = "2027-03", Group = "Insurance" },
            new CatalogItem { Id = "clinic-054", Title = "Cardiology", Subtitle = "3F", Group = "Departments" },
            new CatalogItem { Id = "clinic-055", Title = "Imaging", Subtitle = "B1", Group = "Departments" },
            new CatalogItem { Id = "clinic-056", Title = "Pharmacy", Subtitle = "G", Group = "Departments" },
            new CatalogItem { Id = "clinic-057", Title = "HR", Subtitle = "72", Group = "Vitals" },
            new CatalogItem { Id = "clinic-058", Title = "BP", Subtitle = "118 / 74", Group = "Vitals" },
            new CatalogItem { Id = "clinic-059", Title = "Weight", Subtitle = "64.2 kg", Group = "Vitals" },
            new CatalogItem { Id = "clinic-060", Title = "21:00", Subtitle = "Atorvastatin", Group = "Medications" },
            new CatalogItem { Id = "clinic-061", Title = "Sunday", Subtitle = "D3", Group = "Medications" },
            new CatalogItem { Id = "clinic-062", Title = "Late?", Subtitle = "Call the desk before 15 min.", Group = "Faq" },
            new CatalogItem { Id = "clinic-063", Title = "Records", Subtitle = "PDF in Documents.", Group = "Faq" },
            new CatalogItem { Id = "clinic-064", Title = "Desk", Subtitle = "020 7946 1000", Group = "Help" },
            new CatalogItem { Id = "clinic-065", Title = "After hours", Subtitle = "On-call GP", Group = "Help" },
            new CatalogItem { Id = "clinic-066", Title = "Thu 09:30", Subtitle = "Bring your wearable.", Group = "Notifications" },
            new CatalogItem { Id = "clinic-067", Title = "Rx ready", Subtitle = "Harbour pharmacy", Group = "Notifications" },
            new CatalogItem { Id = "clinic-068", Title = "Share labs", Subtitle = "On", Group = "Settings" },
            new CatalogItem { Id = "clinic-069", Title = "Telehealth", Subtitle = "On", Group = "Settings" }
    ];
}
