namespace NuvyntraLabs.Lumina.Core;

public static class FieldSeed
{
    public const string Collection = "field";

    public static IReadOnlyList<CatalogItem> Items { get; } =
    [
            new CatalogItem { Id = "field-001", Title = "Crew id", Subtitle = "HF-441", Group = "SignIn" },
            new CatalogItem { Id = "field-002", Title = "Password", Subtitle = "secret", Group = "SignIn" },
            new CatalogItem { Id = "field-003", Title = "HF-204", Subtitle = "Inspect pump · Cedar Yard · SLA 16:00", Group = "Home" },
            new CatalogItem { Id = "field-004", Title = "HF-188", Subtitle = "NFC audit · Pier 3 · 11:00", Group = "Home" },
            new CatalogItem { Id = "field-005", Title = "Queue", Subtitle = "2 photos waiting on radio", Group = "Home" },
            new CatalogItem { Id = "field-006", Title = "HF-204", Subtitle = "Inspect pump · Cedar Yard · 09:30", Group = "Jobs" },
            new CatalogItem { Id = "field-007", Title = "HF-188", Subtitle = "NFC audit · Pier 3 · 11:00", Group = "Jobs" },
            new CatalogItem { Id = "field-008", Title = "HF-175", Subtitle = "Print receipt · Harbour desk · 14:00", Group = "Jobs" },
            new CatalogItem { Id = "field-009", Title = "SLA", Subtitle = "Today 16:00", Group = "JobDetail" },
            new CatalogItem { Id = "field-010", Title = "Site", Subtitle = "Yard B", Group = "JobDetail" },
            new CatalogItem { Id = "field-011", Title = "Parts", Subtitle = "Gasket kit", Group = "JobDetail" },
            new CatalogItem { Id = "field-012", Title = "Cedar Yard", Subtitle = "Geofence in", Group = "Sites" },
            new CatalogItem { Id = "field-013", Title = "Pier 3", Subtitle = "0.8 mi", Group = "Sites" },
            new CatalogItem { Id = "field-014", Title = "Harbour Walk", Subtitle = "1.4 mi", Group = "Sites" },
            new CatalogItem { Id = "field-015", Title = "Cedar Yard", Subtitle = "80 m · dwell 5 min", Group = "Geofences" },
            new CatalogItem { Id = "field-016", Title = "Pier 3", Subtitle = "50 m · enter", Group = "Geofences" },
            new CatalogItem { Id = "field-017", Title = "Housing", Subtitle = "OK", Group = "Inspection" },
            new CatalogItem { Id = "field-018", Title = "Gasket", Subtitle = "Replace", Group = "Inspection" },
            new CatalogItem { Id = "field-019", Title = "Tag", Subtitle = "NFC written", Group = "Inspection" },
            new CatalogItem { Id = "field-020", Title = "housing.jpg", Subtitle = "1.8 MB · ready", Group = "Evidence" },
            new CatalogItem { Id = "field-021", Title = "gasket.jpg", Subtitle = "2.1 MB · queued", Group = "Evidence" },
            new CatalogItem { Id = "field-022", Title = "Tag", Subtitle = "04:A3:19:88", Group = "NfcScan" },
            new CatalogItem { Id = "field-023", Title = "Asset", Subtitle = "PUMP-441", Group = "NfcScan" },
            new CatalogItem { Id = "field-024", Title = "Last", Subtitle = "12 Sep", Group = "NfcScan" },
            new CatalogItem { Id = "field-025", Title = "PUMP-441", Subtitle = "Cedar · OK", Group = "Assets" },
            new CatalogItem { Id = "field-026", Title = "GEN-12", Subtitle = "Pier 3 · due", Group = "Assets" },
            new CatalogItem { Id = "field-027", Title = "RADIO-9", Subtitle = "Van · OK", Group = "Assets" },
            new CatalogItem { Id = "field-028", Title = "Hours", Subtitle = "1 842", Group = "AssetDetail" },
            new CatalogItem { Id = "field-029", Title = "Next service", Subtitle = "Oct 2026", Group = "AssetDetail" },
            new CatalogItem { Id = "field-030", Title = "NFC", Subtitle = "04:A3:19:88", Group = "AssetDetail" },
            new CatalogItem { Id = "field-031", Title = "Local", Subtitle = "Gasket replace", Group = "Conflicts" },
            new CatalogItem { Id = "field-032", Title = "Desk", Subtitle = "Gasket OK", Group = "Conflicts" },
            new CatalogItem { Id = "field-033", Title = "Pick", Subtitle = "Local", Group = "Conflicts" },
            new CatalogItem { Id = "field-034", Title = "photo gasket", Subtitle = "Retry 30s", Group = "OfflineQueue" },
            new CatalogItem { Id = "field-035", Title = "NFC write", Subtitle = "Retry 2 min", Group = "OfflineQueue" },
            new CatalogItem { Id = "field-036", Title = "Zebra ZQ", Subtitle = "SPP · paired", Group = "Printers" },
            new CatalogItem { Id = "field-037", Title = "Harbour desk", Subtitle = "BLE · idle", Group = "Printers" },
            new CatalogItem { Id = "field-038", Title = "Work", Subtitle = "Gasket replace", Group = "Receipt" },
            new CatalogItem { Id = "field-039", Title = "Hours", Subtitle = "1.2", Group = "Receipt" },
            new CatalogItem { Id = "field-040", Title = "Sign", Subtitle = "Nia", Group = "Receipt" },
            new CatalogItem { Id = "field-041", Title = "HF-204", Subtitle = "1.2 h", Group = "Timesheet" },
            new CatalogItem { Id = "field-042", Title = "HF-188", Subtitle = "0.8 h", Group = "Timesheet" },
            new CatalogItem { Id = "field-043", Title = "Travel", Subtitle = "0.4 h", Group = "Timesheet" },
            new CatalogItem { Id = "field-044", Title = "Open", Subtitle = "3", Group = "Dashboard" },
            new CatalogItem { Id = "field-045", Title = "Overdue", Subtitle = "0", Group = "Dashboard" },
            new CatalogItem { Id = "field-046", Title = "Queue", Subtitle = "2", Group = "Dashboard" },
            new CatalogItem { Id = "field-047", Title = "pump-441.pdf", Subtitle = "2 pages", Group = "Files" },
            new CatalogItem { Id = "field-048", Title = "yard-b.png", Subtitle = "site plan", Group = "Files" },
            new CatalogItem { Id = "field-049", Title = "PPE", Subtitle = "On", Group = "Checklist" },
            new CatalogItem { Id = "field-050", Title = "Lockout", Subtitle = "On", Group = "Checklist" },
            new CatalogItem { Id = "field-051", Title = "Spotter", Subtitle = "Nia", Group = "Checklist" },
            new CatalogItem { Id = "field-052", Title = "Permit", Subtitle = "CS-19", Group = "Safety" },
            new CatalogItem { Id = "field-053", Title = "Gas", Subtitle = "Clear 08:50", Group = "Safety" },
            new CatalogItem { Id = "field-054", Title = "Radio", Subtitle = "Ch 4", Group = "Safety" },
            new CatalogItem { Id = "field-055", Title = "1", Subtitle = "Cedar Yard", Group = "Route" },
            new CatalogItem { Id = "field-056", Title = "2", Subtitle = "Pier 3", Group = "Route" },
            new CatalogItem { Id = "field-057", Title = "3", Subtitle = "Desk print", Group = "Route" },
            new CatalogItem { Id = "field-058", Title = "Nia", Subtitle = "Gasket kit is in the van.", Group = "Team" },
            new CatalogItem { Id = "field-059", Title = "You", Subtitle = "On site in 10.", Group = "Team" },
            new CatalogItem { Id = "field-060", Title = "HF-204", Subtitle = "SLA in 4 hours", Group = "Notifications" },
            new CatalogItem { Id = "field-061", Title = "Fence", Subtitle = "Entered Cedar Yard", Group = "Notifications" },
            new CatalogItem { Id = "field-062", Title = "Keep screen on", Subtitle = "On", Group = "Settings" },
            new CatalogItem { Id = "field-063", Title = "Offline first", Subtitle = "On", Group = "Settings" }
    ];
}
