namespace NuvyntraLabs.Lumina.Core;

public static class MarketSeed
{
    public const string Collection = "market";

    public static IReadOnlyList<CatalogItem> Items { get; } =
    [
            new CatalogItem { Id = "market-001", Title = "Welcome to Market", Subtitle = "Groceries, plates, and pantry in one aisle.", Group = "Walkthrough" },
            new CatalogItem { Id = "market-002", Title = "Same-day slots", Subtitle = "Couriers from Harbour Studio.", Group = "Walkthrough" },
            new CatalogItem { Id = "market-003", Title = "Pay once", Subtitle = "Cards, wallet, or kitchen tab.", Group = "Walkthrough" },
            new CatalogItem { Id = "market-004", Title = "Email", Subtitle = "demo@lumina.market", Group = "SignIn" },
            new CatalogItem { Id = "market-005", Title = "Password", Subtitle = "secret", Group = "SignIn" },
            new CatalogItem { Id = "market-006", Title = "Full name", Subtitle = "Ada Lovelace", Group = "SignUp" },
            new CatalogItem { Id = "market-007", Title = "Email", Subtitle = "ada@lumina.market", Group = "SignUp" },
            new CatalogItem { Id = "market-008", Title = "Phone", Subtitle = "+44 20 7946 0018", Group = "SignUp" },
            new CatalogItem { Id = "market-009", Title = "Email", Subtitle = "demo@lumina.market", Group = "ForgotPassword" },
            new CatalogItem { Id = "market-010", Title = "OTP", Subtitle = "184392", Group = "ResetPassword" },
            new CatalogItem { Id = "market-011", Title = "New password", Subtitle = "••••••••", Group = "ResetPassword" },
            new CatalogItem { Id = "market-012", Title = "Display name", Subtitle = "Ada", Group = "ProfileSetup" },
            new CatalogItem { Id = "market-013", Title = "Kitchen", Subtitle = "Studio loft", Group = "ProfileSetup" },
            new CatalogItem { Id = "market-014", Title = "Aurora pears", Subtitle = "£3.40 · orchard crate", Group = "Home" },
            new CatalogItem { Id = "market-015", Title = "Cedar chair", Subtitle = "£186 · weekend drop", Group = "Home" },
            new CatalogItem { Id = "market-016", Title = "Harbour ramen", Subtitle = "£14 · 22 min", Group = "Home" },
            new CatalogItem { Id = "market-017", Title = "Produce", Subtitle = "84 items", Group = "Categories" },
            new CatalogItem { Id = "market-018", Title = "Home", Subtitle = "61 items", Group = "Categories" },
            new CatalogItem { Id = "market-019", Title = "Kitchen", Subtitle = "47 items", Group = "Categories" },
            new CatalogItem { Id = "market-020", Title = "Ready to eat", Subtitle = "29 items", Group = "Categories" },
            new CatalogItem { Id = "market-021", Title = "Aurora lamp", Subtitle = "£42", Group = "Catalog" },
            new CatalogItem { Id = "market-022", Title = "Harbour mug", Subtitle = "£18", Group = "Catalog" },
            new CatalogItem { Id = "market-023", Title = "Linen throw", Subtitle = "£64", Group = "Catalog" },
            new CatalogItem { Id = "market-024", Title = "Cedar chair", Subtitle = "£186", Group = "Catalog" },
            new CatalogItem { Id = "market-025", Title = "Finish", Subtitle = "White oak", Group = "ProductDetail" },
            new CatalogItem { Id = "market-026", Title = "Lead time", Subtitle = "5 days", Group = "ProductDetail" },
            new CatalogItem { Id = "market-027", Title = "Rating", Subtitle = "4.8 · 216 reviews", Group = "ProductDetail" },
            new CatalogItem { Id = "market-028", Title = "Cedar lounge", Subtitle = "£186 · wool", Group = "Compare" },
            new CatalogItem { Id = "market-029", Title = "Studio stool", Subtitle = "£92 · leather", Group = "Compare" },
            new CatalogItem { Id = "market-030", Title = "pears", Subtitle = "12 matches", Group = "Search" },
            new CatalogItem { Id = "market-031", Title = "oak chair", Subtitle = "4 matches", Group = "Search" },
            new CatalogItem { Id = "market-032", Title = "ramen", Subtitle = "6 matches", Group = "Search" },
            new CatalogItem { Id = "market-033", Title = "Max price", Subtitle = "£80", Group = "Filters" },
            new CatalogItem { Id = "market-034", Title = "Aisle", Subtitle = "Home", Group = "Filters" },
            new CatalogItem { Id = "market-035", Title = "Window", Subtitle = "Today 4–6", Group = "Filters" },
            new CatalogItem { Id = "market-036", Title = "Linen throw", Subtitle = "£64", Group = "Wishlist" },
            new CatalogItem { Id = "market-037", Title = "Harbour mug", Subtitle = "£18", Group = "Wishlist" },
            new CatalogItem { Id = "market-038", Title = "Aurora pears × 2", Subtitle = "£6.80", Group = "Cart" },
            new CatalogItem { Id = "market-039", Title = "Harbour ramen × 1", Subtitle = "£14.00", Group = "Cart" },
            new CatalogItem { Id = "market-040", Title = "Address", Subtitle = "14 Harbour Walk", Group = "Checkout" },
            new CatalogItem { Id = "market-041", Title = "Slot", Subtitle = "Today 17:30", Group = "Checkout" },
            new CatalogItem { Id = "market-042", Title = "Note", Subtitle = "Leave at studio door", Group = "Checkout" },
            new CatalogItem { Id = "market-043", Title = "Card", Subtitle = "4242 4242 4242 4242", Group = "CardPayment" },
            new CatalogItem { Id = "market-044", Title = "Expiry", Subtitle = "09 / 28", Group = "CardPayment" },
            new CatalogItem { Id = "market-045", Title = "CVC", Subtitle = "317", Group = "CardPayment" },
            new CatalogItem { Id = "market-046", Title = "Visa ··4242", Subtitle = "Ada Lovelace", Group = "SavedCards" },
            new CatalogItem { Id = "market-047", Title = "Kitchen tab", Subtitle = "Harbour Studio", Group = "SavedCards" },
            new CatalogItem { Id = "market-048", Title = "Order", Subtitle = "#LM-1042", Group = "PaymentResult" },
            new CatalogItem { Id = "market-049", Title = "Total", Subtitle = "£20.80", Group = "PaymentResult" },
            new CatalogItem { Id = "market-050", Title = "ETA", Subtitle = "17:52", Group = "PaymentResult" },
            new CatalogItem { Id = "market-051", Title = "#LM-1042", Subtitle = "Packing · £20.80", Group = "Orders" },
            new CatalogItem { Id = "market-052", Title = "#LM-1008", Subtitle = "Delivered · £64.00", Group = "Orders" },
            new CatalogItem { Id = "market-053", Title = "Placed", Subtitle = "Today 16:04", Group = "OrderDetail" },
            new CatalogItem { Id = "market-054", Title = "Courier", Subtitle = "Nia Okonkwo", Group = "OrderDetail" },
            new CatalogItem { Id = "market-055", Title = "Total", Subtitle = "£20.80", Group = "OrderDetail" },
            new CatalogItem { Id = "market-056", Title = "Packed", Subtitle = "16:11", Group = "Tracking" },
            new CatalogItem { Id = "market-057", Title = "Ship", Subtitle = "16:40", Group = "Tracking" },
            new CatalogItem { Id = "market-058", Title = "Door", Subtitle = "17:52", Group = "Tracking" },
            new CatalogItem { Id = "market-059", Title = "Produce", Subtitle = "£6.80", Group = "Invoice" },
            new CatalogItem { Id = "market-060", Title = "Kitchen", Subtitle = "£14.00", Group = "Invoice" },
            new CatalogItem { Id = "market-061", Title = "Total", Subtitle = "£20.80", Group = "Invoice" },
            new CatalogItem { Id = "market-062", Title = "Merchant", Subtitle = "Lumina Market", Group = "Receipt" },
            new CatalogItem { Id = "market-063", Title = "Auth", Subtitle = "184392", Group = "Receipt" },
            new CatalogItem { Id = "market-064", Title = "Total", Subtitle = "£20.80", Group = "Receipt" },
            new CatalogItem { Id = "market-065", Title = "Rating", Subtitle = "5", Group = "Reviews" },
            new CatalogItem { Id = "market-066", Title = "Note", Subtitle = "The oak smells like the workshop.", Group = "Reviews" },
            new CatalogItem { Id = "market-067", Title = "Harbour Walk", Subtitle = "0.4 mi · open", Group = "StoreLocator" },
            new CatalogItem { Id = "market-068", Title = "Cedar Yard", Subtitle = "1.8 mi · closes 20:00", Group = "StoreLocator" },
            new CatalogItem { Id = "market-069", Title = "Studio loft", Subtitle = "14 Harbour Walk", Group = "Addresses" },
            new CatalogItem { Id = "market-070", Title = "Office", Subtitle = "2 Aurora Lane", Group = "Addresses" },
            new CatalogItem { Id = "market-071", Title = "Plan", Subtitle = "Aurora crate", Group = "Subscription" },
            new CatalogItem { Id = "market-072", Title = "Price", Subtitle = "£28 / week", Group = "Subscription" },
            new CatalogItem { Id = "market-073", Title = "Next", Subtitle = "Thursday", Group = "Subscription" },
            new CatalogItem { Id = "market-074", Title = "You", Subtitle = "Can the ramen skip chilli?", Group = "SellerChat" },
            new CatalogItem { Id = "market-075", Title = "Kitchen", Subtitle = "Done. 22 minutes.", Group = "SellerChat" },
            new CatalogItem { Id = "market-076", Title = "Courier nearby", Subtitle = "Nia is 4 minutes out", Group = "Notifications" },
            new CatalogItem { Id = "market-077", Title = "Crate packed", Subtitle = "Thursday aurora crate", Group = "Notifications" },
            new CatalogItem { Id = "market-078", Title = "Dark paper", Subtitle = "Off", Group = "Settings" },
            new CatalogItem { Id = "market-079", Title = "New checkout", Subtitle = "On", Group = "Settings" },
            new CatalogItem { Id = "market-080", Title = "Review prompt", Subtitle = "Later", Group = "Settings" },
            new CatalogItem { Id = "market-081", Title = "Slots", Subtitle = "Same-day until 19:00", Group = "Help" },
            new CatalogItem { Id = "market-082", Title = "Returns", Subtitle = "7 days on home goods", Group = "Help" }
    ];
}
